nohup: ignoring input
  
 Running PREMER with 1 parallel threads...
  Calculating H2 and MI...
 H2, MI calculated in   47.16995     seconds.
  Calculating H3...
 H3, MI3 calculated in    242.5046     seconds.
  Calculating transfer entropy (T)...
 T calculated in:   -8.583164     seconds.
['./PREMERlin64.out', 'insilico_size100_1_knockouts', '100', '10', '2', '1', '1', 'MI', '1']
Too many plots to plot
Traceback (most recent call last):
  File "pyPREMER.py", line 277, in <module>
    plot_graph(Output, show=Args.plotMI)
  File "/mnt/dados/murilo/GRN_portugal/grn_pt/grnPyScripts/PREMER/pyPREMER_v2_1/source/PlotMI.py", line 63, in plot_graph
    plt.scatter(Y[0], Y[1], color='red', s=50)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3461, in scatter
    ax = gca()
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 969, in gca
    return gcf().gca(**kwargs)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/home/murilobarbosa/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
Starting pos processing...
